version: '2'

# Complementary services, not part of geOrchestra core.
# They are made to ease your life as a developer.
# **NOT** production ready !

services:
  georchestra.mydomain.org:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/ssl:/etc/traefik/ssl/
      - /dev/null:/traefik.toml
    command: --web --docker --logLevel=INFO --docker.domain='mydomain.org' --docker.exposedbydefault='false' --docker.watch --entryPoints='Name:https Address::443 TLS:/etc/traefik/ssl/georchestra-docker_umrthema_univ-fcomte_fr.crt,/etc/traefik/ssl/georchestra-docker.umrthema.univ-fcomte.fr.key' --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --defaultentrypoints=http,https

  proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sp"
      - "traefik.frontend.rule=Host:georchestra-docker.umrthema.univ-fcomte.fr"
      - "traefik.frontend.passHostHeader=true"

  smtp:
    build: docker/smtp/smtp-sink
    image: camptocamp/smtp-sink:latest

#  courier-imap:
#    build: docker/smtp/courier-imap
#    image: camptocamp/courier-imap:latest
#    volumes_from:
#      - smtp:rw

#  webmail:
#    build: docker/smtp/webmail
#    image: camptocamp/sqwebmail:latest
#    ports:
#      - "8081:80"
#    volumes_from:
#      - smtp:rw

  geodata:
    build: docker/ssh_data
    image: georchestra/ssh_data:latest
    ports:
      - "2222:22"
    volumes:
      - geoserver_geodata:/mnt/geoserver_geodata

  geosync:
    build: docker/geosync
    image: mshe/geosync
    environment:
      - SERVER_URL=https://georchestra-docker.umrthema.univ-fcomte.fr
      - OCL_URL=https://owncloud-mshe.univ-fcomte.fr
      - OPEN_USER_DAVPASS=Lesoleilauzenith
      - RSCT_USER_DAVPASS=Lesoleilauzenith
    ports:
      - "2222:22"
    privileged: True
    cap_add:
      - SYS_ADMIN
    volumes:
      - geosync_home:/home
      - /dev/fuse:/dev/fuse
      - ./docker/ssl/DigiCertCA.crt:/usr/local/share/ca-certificates/DigiCertCA.crt:ro
    extra_hosts:
      - "georchestra-docker.umrthema.univ-fcomte.fr:172.20.74.83"
