#!/bin/bash

echo "Setting saslauth files for LDAP"

# /etc/ldap/ldap.conf
perl -p -i -e "s/dc=georchestra,dc=org/${SLAPD_DC_STRING}/" /tmp/LDAP/ldap.conf
cp /tmp/LDAP/ldap.conf  /etc/ldap/ldap.conf

# /etc/ldap/sasl2/slapd.conf
cp /tmp/LDAP/slapd.conf /etc/ldap/sasl2/slapd.conf

# /etc/saslauthd.conf
perl -p -i -e "s/dc=ad,dc=georchestra,dc=org/${AD_DC_STRING}/" /etc/saslauthd.conf
perl -p -i -e "s/ad-server.georchestra.org/${AD_SERVER}/"      /etc/saslauthd.conf
perl -p -i -e "s/ad_secret/${AD_PASSWORD}/"                    /etc/saslauthd.conf

# /root/ad2ldap_sync.py
echo "Template ad2ldap_sync.py"
perl -p -i -e "s/ad.georchestra.org/${AD_DOMAIN}/"             /root/ad2ldap_sync.py
perl -p -i -e "s/dc=ad,dc=georchestra,dc=org/${AD_DC_STRING}/" /root/ad2ldap_sync.py
perl -p -i -e "s/dc=georchestra,dc=org/${SLAPD_DC_STRING}/"    /root/ad2ldap_sync.py

# /root/.ldap.conf (attention à l'ordre de passage des substitutions)
perl -p -i -e "s/ad_secret/${AD_PASSWORD}/"                    /root/.ldap.conf
perl -p -i -e "s/dc=ad,dc=georchestra,dc=org/${AD_DC_STRING}/" /root/.ldap.conf
perl -p -i -e "s/ad-server.georchestra.org/${AD_SERVER}/"      /root/.ldap.conf
perl -p -i -e "s/dc=georchestra,dc=org/${SLAPD_DC_STRING}/"    /root/.ldap.conf

