#!/bin/bash

# le serveur DNS de google, 8.8.8.8, ne résoud pas les adresses privées.
# or, notre AD est dans une zone privée.

echo "Setting resolv.conf"
perl -p -i -e "s/nameserver.org/${NAME_SERVER}/" /tmp/LDAP/resolv.conf
cat /tmp/LDAP/resolv.conf >> /etc/resolv.conf

